### ISSUE TITLE
include a button to leave to silver inside of the slot machines

### ISSUE THREAD

**Issue by tomvd** [tomvd/HospitalityCasino#2]
include a button to leave to silver inside of the slot machines

**Comment by tomvd** [comment]
perhaps a change to vending machine adding a gizmo to set an amount to only empty it above this amount

**Comment by OrionFive** [comment]
That might be a good idea. Maybe the attractiveness and fun (when winning the jackpot) of a slot machine would depend on how much silver is inside?

One thing to be careful with is that there shouldn't be a linear way for players with uncountable silver amounts to "buy" happiness.

**Comment by tomvd** [comment]
Closing this, as it was done on the vending machine comp. A similar idea might be useful on the cash registers. But thinking that should be in the mod settings, because there is no added value of  a separate setting for each register.
As for attractiveness and fun depending on silver: one of the rules I wanted to keep is that the machines still work as regular recreation items with the same functionality whether you charge for it or not.
